name: Example pynt yml 
on: 
  workflow_dispatch:
    inputs: 
      comment: 
        type: string 
        default: "API Security tests"

env:
  PYNT_CREDENTIALS: ${{ secrets.YOURPYNTID }}

jobs:
 api-security:
  runs-on: ubuntu-latest

  steps: 
    - name: install pynt cli
      run: | 
        python3 -m pip install --upgrade pyntcli 
    - name: get postman_collection collection 
      run: | 
        curl https://raw.githubusercontent.com/ishaquee/Pynt_CICD/main/New%20Collection.postman_collection.json -o postman_collection.json 
    - name: run pynt with newman integration 
      run: | 
        pynt newman --collection postman_collection.json --reporters
